name: Bug Report
description: File a bug report
title: "[BUG] "
type: bug
labels:
  - bug

body:
  - type: markdown
    attributes:
      value: |
        **Thank you for taking the time to report a bug!**
        If this is a security issue please see [SECURITY.md](SECURITY.md) for more information.
  
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true

  - type: input
    id: package-version
    attributes:
      label: Package version
      description: What version of the package are you using?
      placeholder: ex. 1.2.3
    validations:
      required: true

  - type: input
    id: go-version
    attributes:
      label: Golang version
      description: What version of golang are u using?
      placeholder: ex. 1.23 (run `go version` to find out)
    validations:
      required: false

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

  - type: textarea
    id: what-expected
    attributes:
      label: What did you expect to happen?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you expected!
      value: "I expected this to work!"
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Please provide detailed steps to reproduce the bug.
      placeholder: Tell us how to reproduce the bug!
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
      description: Please provide any additional information that may be helpful in diagnosing the issue.
      placeholder: Tell us more!
    validations:
      required: false
